package AccountSystem;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.TableModel;

/**
 *
 * @author abu
 */
public class billpage extends javax.swing.JFrame {

    int invno=getinNo();
    public billpage() {
        initComponents();
        inlbl.setText(String.valueOf(invno));
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cntct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        protxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        qttxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jf3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pritxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jf5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jf6 = new javax.swing.JTextField();
        jbadd = new javax.swing.JButton();
        jldate = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        inlbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        gt = new javax.swing.JLabel();
        jl3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Make Bills ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(465, 465, 465))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel2.setText("Customer Name");

        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });

        jLabel3.setText("Address :-");

        jLabel4.setText("City :-");

        jLabel7.setText("Contact :-");

        cntct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cntctActionPerformed(evt);
            }
        });

        jLabel8.setText("State");

        jLabel9.setText("Pincode :-");

        jLabel10.setText("Date :-");

        jLabel11.setText("Product :");

        protxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protxtActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantity :");

        qttxt.setText("0");

        jLabel13.setText("Quantity Type :");

        jf3.setText("PCS.");
        jf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Price :");

        pritxt.setText("0");
        pritxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pritxtActionPerformed(evt);
            }
        });

        jLabel15.setText("Tax :");

        jf5.setText("0");

        jLabel16.setText("Discount :");

        jf6.setText("0");

        jbadd.setText("Add Item");
        jbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddActionPerformed(evt);
            }
        });

        jldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jldate.setText("00/00/00");

        jLabel19.setText("Invoice No :-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cn)
                            .addComponent(cntct, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ad)
                            .addComponent(st, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel16)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ct, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(pc))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel11)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel12)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel13)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(protxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(qttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jf3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(pritxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jf5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jf6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbadd)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(28, 28, 28)
                                .addComponent(jldate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(105, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(ct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(inlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cntct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jldate))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(protxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pritxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbadd)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Quantity Type", "Price", "Tax", "GST (INR)", "Discount", "Total"
            }
        ));
        jScrollPane2.setViewportView(jt1);
        if (jt1.getColumnModel().getColumnCount() > 0) {
            jt1.getColumnModel().getColumn(0).setMinWidth(150);
            jt1.getColumnModel().getColumn(0).setPreferredWidth(150);
            jt1.getColumnModel().getColumn(0).setMaxWidth(150);
            jt1.getColumnModel().getColumn(1).setMinWidth(100);
            jt1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jt1.getColumnModel().getColumn(1).setMaxWidth(100);
            jt1.getColumnModel().getColumn(2).setMinWidth(90);
            jt1.getColumnModel().getColumn(2).setPreferredWidth(90);
            jt1.getColumnModel().getColumn(2).setMaxWidth(90);
            jt1.getColumnModel().getColumn(3).setMinWidth(90);
            jt1.getColumnModel().getColumn(3).setPreferredWidth(90);
            jt1.getColumnModel().getColumn(3).setMaxWidth(90);
            jt1.getColumnModel().getColumn(4).setMinWidth(70);
            jt1.getColumnModel().getColumn(4).setPreferredWidth(70);
            jt1.getColumnModel().getColumn(4).setMaxWidth(70);
            jt1.getColumnModel().getColumn(5).setMinWidth(100);
            jt1.getColumnModel().getColumn(5).setPreferredWidth(100);
            jt1.getColumnModel().getColumn(5).setMaxWidth(100);
            jt1.getColumnModel().getColumn(6).setMinWidth(100);
            jt1.getColumnModel().getColumn(6).setPreferredWidth(100);
            jt1.getColumnModel().getColumn(6).setMaxWidth(100);
            jt1.getColumnModel().getColumn(7).setMinWidth(100);
            jt1.getColumnModel().getColumn(7).setPreferredWidth(100);
            jt1.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        gt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gt.setText("GRAND TOTAL :-");

        jl3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl3.setText("0000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gt))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(gt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setText("SAVE ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 0, 255));
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 102));
        jButton4.setText("DROP INVOICE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jt2.setBackground(new java.awt.Color(0, 204, 204));
        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CGST PAYABLE :-", ""},
                {"SGST PAYABLE :-", null},
                {"TOTAL GST :-", null}
            },
            new String [] {
                "TOTAL ", "AMOUNT  (INR)"
            }
        ));
        jt2.setRowHeight(25);
        jScrollPane1.setViewportView(jt2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton4)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jButton5.setBackground(new java.awt.Color(255, 0, 51));
        jButton5.setText("DELETE ITEM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel17.setText("SELECT THE ROW OF ITEM BEFORE");

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("HITTING THE DELETE BUTTON");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//invoice number
    private int getinNo(){
        int id=0;
        try {
            dbconn.connect();
            ResultSet rs=dbconn.stm.executeQuery("select customer_id from customer");
            while(rs.next())
                 id=rs.getInt("customer_id");
            dbconn.discoonect();
            id++;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    
    // coding of the date
    void date()
    {
        Date d=new Date();
        SimpleDateFormat s= new SimpleDateFormat("yyyy-MM-dd");
        jldate.setText(s.format(d));
    }
    public static String[] getdata()
            {
                String[] data=new String[5];
                data[0]=cnam;
                data[1]=add;
                data[2]=con;
                data[3]=gtot;
                data[4]=inv;
                return data;
            }
public static DefaultTableModel gettab1()
{
    DefaultTableModel mod=(DefaultTableModel)tm;
    return mod;
}
public static DefaultTableModel gettab2(){
    DefaultTableModel mod=(DefaultTableModel)tm1;
    return mod;
}
    //get data from table
   private void gettabdata(){
        DefaultTableModel mod=(DefaultTableModel)jt1.getModel();
        int i=0;
        while(i<mod.getRowCount()){
            String pro=String.valueOf(mod.getValueAt(i,0));
            String qu=String.valueOf(mod.getValueAt(i, 1));
            String qt=String.valueOf(mod.getValueAt(i, 2));
            String pri=String.valueOf(mod.getValueAt(i, 3));
            String tax=String.valueOf(mod.getValueAt(i, 4));
            String gst=String.valueOf(mod.getValueAt(i, 5));
            String dis=String.valueOf(mod.getValueAt(i, 6));
            String tot=String.valueOf(mod.getValueAt(i, 7));
            try {
                dbconn.stm.execute("insert into product values('"+invno+"','"+pro+"','"+qu+"','"+qt+"','"+pri+"','"+tax+"','"+gst+"','"+dis+"','"+tot+"')");
            } catch (SQLException ex) {
                Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
            }
            i++;
        }
        
    }
    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnActionPerformed

    private void jf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf3ActionPerformed
    
    }//GEN-LAST:event_jf3ActionPerformed
static TableModel tm,tm1;
static String gtot,inv;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cnam=cn.getText();
        add=ad.getText();
        con=cntct.getText();
        tm=jt1.getModel();
        tm1=jt2.getModel();
        gtot=jl3.getText();
        inv=inlbl.getText();
        Print_form pform = new Print_form();
        pform.setdata();
        pform.setVisible(true);
        super.setVisible(false);
        //pform.startprinting();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddActionPerformed
    DefaultTableModel model=(DefaultTableModel) jt1.getModel();

        double price=Double.parseDouble(pritxt.getText());
           double qt=Double.parseDouble(qttxt.getText());
           
        double tax=Double.parseDouble(jf5.getText());
        if(tax!=5 && tax!=12 && tax!=18 && tax!=28) // checking conditions for the gst/tax type
            
        {
            JOptionPane.showMessageDialog(this,"Tax type is not supported Please Enter tax Type (5,12,18,28)");
            JOptionPane.showMessageDialog(this,"The default gst value of tax will be added (18%)");
            tax=18;
        }
        
        double dis=Double.parseDouble(jf6.getText());
 double wgst_total=price*qt;
          
            
       
        double gst=wgst_total*(tax/100);
        double cgst=gst/2;
        double sgst=gst/2;
        double discount=((price*qt)+gst)*(dis/100);
                double total = (price*qt)+gst-discount;
                
                double gtotal=0;
                double total_gst=0;
               double total_dis=0;
               
       
try{
                model.addRow(new Object[]{protxt.getText(),qttxt.getText(),jf3.getText(),pritxt.getText(),String.valueOf(tax),String.valueOf(gst),jf6.getText(),String.valueOf(total)});
                
}catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
}

// getting the sum of the table rows
 // sum of rows total,total gst,total discount
 
for(int i=0;i<jt1.getRowCount();i++)
{
 double a=Double.parseDouble((String) jt1.getValueAt(i, 7));
 double b=Double.parseDouble((String) jt1.getValueAt(i, 5));
 double c=Double.parseDouble((String) jt1.getValueAt(i, 6));
 gtotal+=a;
 total_gst+=b;
 total_dis+=c;
}
double tcgst=total_gst/2;
double tsgst=total_gst/2; 
jl3.setText(gtotal+"");
protxt.setText(null);
qttxt.setText("0");
jf3.setText("PCS.");
pritxt.setText("0");
jf5.setText("0");
jf6.setText("0");



//setting the table 2 values i.e. TOTAL TABLE 


jt2.setValueAt(tcgst, 0, 1);
jt2.setValueAt(tsgst, 1, 1);
jt2.setValueAt (total_gst,2,1);

// TODO add your handling code here:
    }//GEN-LAST:event_jbaddActionPerformed

    private void pritxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pritxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pritxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
DefaultTableModel model=(DefaultTableModel) jt1.getModel();
// get selected row here 
try{
        int selected_Row = jt1.getSelectedRow();
        
model.removeRow(selected_Row);


DefaultTableModel model_2=(DefaultTableModel) jt2.getModel();
}catch(Exception ex){
    JOptionPane.showMessageDialog(this,"Please Select a Row And Then Hit the DElete Button");
}
// adding the function of the refresh the form
      double price=Double.parseDouble(pritxt.getText());
           double qt=Double.parseDouble(qttxt.getText());
           
        double tax=Double.parseDouble(jf5.getText());
        double dis=Double.parseDouble(jf6.getText());
 double wgst_total=price*qt;
          
            
       
        double gst=wgst_total*(tax/100);
        double cgst=gst/2;
        double sgst=gst/2;
        double discount=((price*qt)+gst)*(dis/100);
                double total = (price*qt)+gst-discount;
                
                double gtotal=0;
                double total_gst=0;
               double total_dis=0;
               for(int i=0;i<jt1.getRowCount();i++)
{
 double a=Double.parseDouble((String) jt1.getValueAt(i, 7));
 double b=Double.parseDouble((String) jt1.getValueAt(i, 5));
 double c=Double.parseDouble((String) jt1.getValueAt(i, 6));
 gtotal+=a;
 total_gst+=b;
 total_dis+=c;
}
double tcgst=total_gst/2;
double tsgst=total_gst/2; 
jl3.setText(gtotal+"");
//setting the table 2 values i.e. TOTAL TABLE 
jt2.setValueAt(tcgst, 0, 1);
jt2.setValueAt(tsgst, 1, 1);
jt2.setValueAt (total_gst,2,1);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int p =JOptionPane.showConfirmDialog(null,"DO you really want to drop the invoice ?", "Drop_Invoice",JOptionPane.YES_NO_OPTION);  
if(p==0)
{
  
    new Main().setVisible(true);
    super.setVisible(false);
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cntctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cntctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cntctActionPerformed
static String cnam,add,con;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       if(cn.getText().trim().length()==0||pc.getText().trim().length()==0)
           JOptionPane.showMessageDialog(null, "You cannot leave empty");
       else{
        try {
             cnam=cn.getText();
             add=ad.getText();
            String city=ct.getText();
            con=cntct.getText();
            String state=st.getText();
            String pin=pc.getText();
            dbconn.connect();
            dbconn.stm.execute("insert into customer values('"+invno+"','"+cnam+"','"+add+"','"+city+"','"+con+"','"+state+"','"+pin+"','"+jldate.getText()+"','"+jl3.getText()+"')");
            gettabdata();
            dbconn.discoonect();
            JOptionPane.showMessageDialog(null, "successfull");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(billpage.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void protxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cntct;
    private javax.swing.JTextField ct;
    private javax.swing.JLabel gt;
    private javax.swing.JLabel inlbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbadd;
    private javax.swing.JTextField jf3;
    private javax.swing.JTextField jf5;
    private javax.swing.JTextField jf6;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jldate;
    private javax.swing.JTable jt1;
    private javax.swing.JTable jt2;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField pritxt;
    private javax.swing.JTextField protxt;
    private javax.swing.JTextField qttxt;
    private javax.swing.JTextField st;
    // End of variables declaration//GEN-END:variables
}

